version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always
  
  consumer:
    build:
      context: .
      dockerfile: redis_stream/Dockerfile
    container_name: consumer
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - EXTERNAL_API_URL=${EXTERNAL_API_URL}
      - GROUP_NAME=${GROUP_NAME}
      - STREAM_NAME=${STREAM_NAME}
      - RETRY_STREAM_NAME=${RETRY_STREAM_NAME}
    restart: unless-stopped

volumes:
  redis_data:
